### DISCUSSION TITLE
Log location

### DISCUSSION THREAD

**Discussion by bearded-papa** [luigi311/JellyPlex-Watched#153] [Q&A] [answered]
In the docker-compose file there is a reference in the enviroment variable saying that logs are in /tmp/log.log but I am unable to find them on my syatem. Where are they?

**Comment by luigi311** [comment]
they wont exist in your host machine unless you mount where they are being output to. by default im not mounting anything so you need to add a mount path into the docker compose and point the log/mark file to that path.

**Reply by bearded-papa** [reply]
no matter how i try to mount a volume i keep getting the following

jellyplex-watched  | PermissionError: [Errno 13] Permission denied: '/tmp/log.log'

```yaml
version: "3"
services:
  jellyplex-watched:
    image: luigi311/jellyplex-watched:latest
    container_name: jellyplex-watched
    restart: always
    volumes:
      - ./tmp:/tmp/
    environment:
      - DRYRUN=False
      - DEBUG=True
      - DEBUG_LEVEL=info
      - RUN_ONLY_ONCE=False
      - SLEEP_DURATION=3600
      - LOGFILE=/tmp/log.log
      - MARKFILE=/tmp/mark.log
```
I have even created the files and change ownership of the directory/files from root to my user as that sometimes fixes issues like this

![image](https://github.com/luigi311/JellyPlex-Watched/assets/143163316/12f926aa-224f-477e-8328-47ff497a0cce)
