### ISSUE TITLE
[BUG] Some TV episodes not syncing

### ISSUE THREAD

**Issue by shadshack** [luigi311/JellyPlex-Watched#214]
**Describe the bug**
Some episodes of TV shows aren't syncing between Plex and Jellyfin. I had everything synced from what I could tell, but then when I watched two episodes of a TV show, it never shows those as watched on Jellyfin. There are no errors or messages about those episodes failing to sync in the logs.

Specific episode detail to look at in the logs:
Show name: "I Got a Cheat Skill in Another World and Became Unrivaled in the Real World, Too"
S01E11 and 12
Title of episode 12: "The Mysterious Assailant" is a unique string to search for

The logs show that it is Watched, but then later on shows this:
[DEBUG]: Plex: Skipping show I Got a Cheat Skill in Another World and Became Unrivaled in the Real World, Too as it is not in mark list for plexUsername

I'm not sure why it's not working.

**To Reproduce**
1. Sync all media
2. See that it's correct
3. Watch new episode on Plex
4. Allow JellyPlex-Watched to run a sync
5. Episode not marked as Watched on Jellyfin

**Expected behavior**
Newly watched Episodes should be synced between the two servers.

**Logs**
If applicable, add logs to help explain your problem ideally with DEBUG set to true, be sure to remove sensitive information
[log.log](https://github.com/user-attachments/files/18014104/log.log)

**Type:**
- [x] Docker Compose (via Portainer)
- [ ] Docker
- [ ] Unraid
- [ ] Native

**Additional context**
The file mark.log is not being created. I assume because it is not thinking there's anything to sync? I'm not sure.

Compose file:
```yaml
version: '3.3'
services:
  jellyplex-watched:
    image: luigi311/jellyplex-watched:latest
    container_name: jellyplex-watched
    volumes:
      - ./jellyplex-watched-data:/app/data
    env_file:
      - stack.env
    restart: unless-stopped
```

.env:
```
DRYRUN=False
DEBUG=True
DEBUG_LEVEL=debug
RUN_ONLY_ONCE=False
SLEEP_DURATION=3600
LOGFILE=/app/data/log.log
MARK_FILE=/app/data/mark.log
REQUEST_TIMEOUT=300
GENERATE_GUIDS=True
GENERATE_LOCATIONS=True
MAX_THREADS=2
USER_MAPPING={"plexUsername":"jellyfinUsername"}
WHITELIST_USERS=jellyfinUsername
PLEX_BASEURL=https://plex.domain.com
PLEX_TOKEN=**************
SSL_BYPASS=False
JELLYFIN_BASEURL=https://jellyfin.domain.com
JELLYFIN_TOKEN=****************
SYNC_FROM_PLEX_TO_JELLYFIN=True
SYNC_FROM_JELLYFIN_TO_PLEX=True
LIBRARY_MAPPING={ "TV Shows": "TV", "Anime": "TV Shows" }
```
