### ISSUE TITLE
[Need Help] Attempt to decode JSON with unexpected mimetype: text/html', url=URL('....')

### ISSUE THREAD

**Issue by vp-en** [luigi311/JellyPlex-Watched#46]
Hey!

I'm getting this error when using your lovely software:

Output from the `log.log`:
https://paste.ec/paste/jmH-GoOH#qetLghapEmczdLcCZ1uFzeSBaAQ8T7xaa7yHzjxjfFT

I'm running it in docker.

My `docker-compose.yml` setup:
```
version: "3.9"

services:
  jellyplexwatched:
    container_name: jellyplexwatched
    image: luigi311/jellyplex-watched:latest
    labels:
     - "org.hotio.pullio.notify=true"
     - "org.hotio.pullio.update=true"
     - "org.hotio.pullio.generic.webhook=https://notifiarr.com/api/v1/notification/pullio/xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx"
     - "autoheal=true"
    volumes:
      - /opt/docker-all/jellyplexwatched/config.env:/app/.env
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
```

My `config.env` (with URLs etc redacted):
https://paste.ec/paste/V0p7h0Fa#4QWxivibZG60U8eM1EDRLyn8j5QEC7KC17+j44upsfi

My NGINX file for my `jellyfin.domain.com`, if that matters at all. I'm just using the official nginx reverse proxy from [the jellyfin docs](https://jellyfin.org/docs/general/networking/nginx/):
https://paste.ec/paste/mLYMPSIM#vUgW46tgSt59ACOIffnI9arMq8OjKoGZ7TTnXHxje9k
