### ISSUE TITLE
How to use compose file in portainer?

### ISSUE THREAD

**Issue by renetsk** [luigi311/JellyPlex-Watched#59]
Hello,
scripts works perfect. Want to create stack in my portainer, how to do that please?

```
version: "3"
services:
  jellyplex:
    image: luigi311/jellyplex-watched:latest
    container_name: jellyplex
    env_file:
    - /home/user/data/jellyplex/.env:/app/.env
    restart: unless-stopped
```

Still getting this error

```
Deployment error
open /home/user/data/jellyplex/.env:/app/.env: no such file or directory 
```

**Comment by JChris246** [comment]
Setting the env file in compose yml with `env_file` should simply be the path to the env file: 

```yml
env_file:
    - /home/user/data/jellyplex/.env
```

**Comment by luigi311** [comment]
I havent used portainer all that much but the following docker compose file does work by itself.

```
version: '3.1'

services:
  jellyplex-watched:
    image: luigi311/jellyplex-watched:latest
    container_name: jellyplex-watched
    restart: always
    pull_policy: always
    volumes:
      - .env:/app/.env

```
